name = "CellularAutomataGTK"
uuid = "db222a54-9a4e-11e9-2a63-0f03ae0fd449"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
